In [2]:
import numpy as np

array = np.arange(1,10).reshape((3,3))
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
int(array[0,0])
int(array[2,2])

np.int64(9)

In [8]:
display(array)
array[:2,1:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[2, 3],
       [5, 6]])

In [12]:
display(array)
display(array[2])
display(array[2,:])
display(array[2:,:])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([7, 8, 9])

array([7, 8, 9])

array([[7, 8, 9]])

In [14]:
display(array)
array[:,:2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2],
       [4, 5],
       [7, 8]])

In [16]:
display(array)
display(array[1,:2])
array[1:2,:2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([4, 5])

array([[4, 5]])